# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/ClientServer/Pipelines/Transition/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  MessageRemote2A: require './MessageRemote2A'
  MessageRemote2B: require './MessageRemote2B'
  UserRemote2A:    require './UserRemote2A'   
  UserRemote2B:    require './UserRemote2B'   