# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/ClientServer/Pipelines/Transition/namespace.coffee

module.exports = (require '../namespace').addNamespace('Transition', class Transition extends Neptune.PackageNamespace)
