// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServer/Pipelines/Transition/namespace.js

module.exports = require('../namespace').addNamespace(
  'Transition',
  class Transition extends Neptune.PackageNamespace {}
);
