# generated by Neptune Namespaces v0.3.0
# file: tests/art/ery/handlers/index.coffee

(module.exports = require './namespace')
.addModules
  TimestampFilter:  require './time_stamp_handler'
  ValidationFilter: require './validation_handler'
