# generated by Neptune Namespaces v0.3.0
# file: tests/art/ery/handlers/index.coffee

(module.exports = require './namespace')
.addModules
  TimeStampHandler:  require './time_stamp_handler'
  ValidationHandler: require './validation_handler'