# generated by Neptune Namespaces v0.3.0
# file: tests/art/ery/handlers/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Handlers ||
Ery.addNamespace 'Handlers', class Handlers extends Neptune.Base
  ;