# generated by Neptune Namespaces v0.1.0
# file: tests/art/ery/handlers/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Handlers ||
Ery.addNamespace class Handlers extends Neptune.Base
  ;