# generated by Neptune Namespaces v0.6
# file: tests/Art/Ery/Flux/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Flux ||
Ery.addNamespace 'Flux', class Flux extends Neptune.Base
  ;