# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/.Server/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Server ||
Ery.addNamespace 'Server', class Server extends Neptune.Base
  ;
