# generated by Neptune Namespaces v0.5
# file: Art/Ery/-Flux/index.coffee

module.exports = require './namespace'
.addModules
  ArtEryFluxModel:      require './ArtEryFluxModel'     
  ArtEryQueryFluxModel: require './ArtEryQueryFluxModel'