// generated by Neptune Namespaces v4.x.x
// file: Art.Ery/Filters/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Filters'))
.addModules({
  AfterEventsFilter:                   require('./AfterEventsFilter'),
  DataUpdatesFilter:                   require('./DataUpdatesFilter'),
  LinkFieldsFilter:                    require('./LinkFieldsFilter'),
  LinkFieldsFilter2:                   require('./LinkFieldsFilter2'),
  LinkFieldsFilter2LegacyApiDecode:    require('./LinkFieldsFilter2LegacyApiDecode'),
  LinkFieldsFilter2LegacyApiEncode:    require('./LinkFieldsFilter2LegacyApiEncode'),
  LinkFieldsFilter2Transition2BFilter: require('./LinkFieldsFilter2Transition2BFilter'),
  PrefetchedRecordsFilter:             require('./PrefetchedRecordsFilter'),
  TimestampFilter:                     require('./TimestampFilter'),
  UniqueIdFilter:                      require('./UniqueIdFilter'),
  UserOwnedFilter:                     require('./UserOwnedFilter'),
  UuidFilter:                          require('./UuidFilter'),
  ValidationFilter:                    require('./ValidationFilter')
});