// generated by Neptune Namespaces v4.x.x
// file: Art.Ery/Filters/namespace.js

module.exports = require('../namespace').addNamespace(
  'Filters',
  class Filters extends Neptune.PackageNamespace {}
);
