# generated by Neptune Namespaces v1.x.x
# file: Art/Ery/.Filters/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Filters'
.addModules
  LinkFieldsFilter:           require './LinkFieldsFilter'          
  SetUserIdFromSessionFilter: require './SetUserIdFromSessionFilter'
  TimestampFilter:            require './TimestampFilter'           
  Tools:                      require './Tools'                     
  UuidFilter:                 require './UuidFilter'                
  ValidationFilter:           require './ValidationFilter'          