// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/index.js

(module.exports = require('./namespace'))

.addModules({
  AuthPipeline:     require('./AuthPipeline'),
  Config:           require('./Config'),
  FilterBase:       require('./FilterBase'),
  SimplePipeline:   require('./SimplePipeline'),
  UpdateAfterMixin: require('./UpdateAfterMixin')
});
require('./Filters');
require('./Flux');