# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Both/namespace.coffee

module.exports = (require '../namespace').addNamespace('Both', class Both extends Neptune.PackageNamespace)
require './Filters/namespace';
require './Flux/namespace'