// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/namespace.js

module.exports = require('../namespace').addNamespace(
  'Both',
  class Both extends Neptune.PackageNamespace {}
);
require('./Filters/namespace');
require('./Flux/namespace');