# generated by Neptune Namespaces v0.5
# file: tests/Art/Ery/Filters/index.coffee

module.exports = require './namespace'
.addModules
  Order:            require './Order'           
  TimestampFilter:  require './TimestampFilter' 
  UuidFilter:       require './UuidFilter'      
  ValidationFilter: require './ValidationFilter'