# generated by Neptune Namespaces v0.5.0
# file: tests/art/ery/filters/index.coffee

module.exports = require './namespace'
.addModules
  Order:            require './order'            
  TimestampFilter:  require './timestamp_filter' 
  ValidationFilter: require './validation_filter'