# generated by Neptune Namespaces v0.5
# file: tests/art/ery/Filters/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Filters ||
Ery.addNamespace 'Filters', class Filters extends Neptune.Base
  ;