# generated by Neptune Namespaces v0.6
# file: tests/Art/Ery/Filters/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Filters ||
Ery.addNamespace 'Filters', class Filters extends Neptune.Base
  ;