# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/namespace.coffee

Art = require '../namespace'
module.exports = Art.Ery ||
Art.addNamespace 'Ery', class Ery extends Neptune.Base
  ;
require './Filters/namespace'