// generated by Neptune Namespaces v4.x.x
// file: Art.Ery/.Flux/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Flux'))
.addModules({
  ArtEryFluxModel:      require('./ArtEryFluxModel'),
  ArtEryQueryFluxModel: require('./ArtEryQueryFluxModel')
});