// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServer/index.js

(module.exports = require('./namespace'))

.addModules({
  AuthRequests:            require('./AuthRequests'),
  ClientFailures:          require('./ClientFailures'),
  CompoundKeys:            require('./CompoundKeys'),
  DataUpdatesFilter:       require('./DataUpdatesFilter'),
  FilterLocationRequests:  require('./FilterLocationRequests'),
  KeyFieldsMixin:          require('./KeyFieldsMixin'),
  LinkFieldsFilter2Remote: require('./LinkFieldsFilter2Remote'),
  MyRemoteRequests:        require('./MyRemoteRequests'),
  Sessions:                require('./Sessions'),
  StandardImport:          require('./StandardImport'),
  StaticAssets:            require('./StaticAssets')
});
require('./Pipelines');