// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServer/namespace.js

module.exports = require('../namespace').addNamespace(
  'ClientServer',
  class ClientServer extends Neptune.PackageNamespace {}
);
require('./Pipelines/namespace');