# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/ClientServer/namespace.coffee

module.exports = (require '../namespace').addNamespace('ClientServer', class ClientServer extends Neptune.PackageNamespace)
require './Pipelines/namespace'