# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/Core/Pipeline/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Aliases:        require './Aliases'       
  CustomRequests: require './CustomRequests'
  Failures:       require './Failures'      
  Filters:        require './Filters'       
  Handlers:       require './Handlers'      
  Subrequests:    require './Subrequests'   