# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/Core/Pipeline/namespace.coffee

Core = require '../namespace'
module.exports = Core.Pipeline ||
Core.addNamespace 'Pipeline', class Pipeline extends Neptune.Base
  ;
