# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Core/Pipeline/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Aliases:        require './Aliases'       
  CustomRequests: require './CustomRequests'
  Failures:       require './Failures'      
  Handlers:       require './Handlers'      
  KeyFieldsMixin: require './KeyFieldsMixin'
  Subrequests:    require './Subrequests'   