// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/Pipeline/index.js

(module.exports = require('./namespace'))

.addModules({
  Aliases:        require('./Aliases'),
  CustomRequests: require('./CustomRequests'),
  Failures:       require('./Failures'),
  Handlers:       require('./Handlers'),
  KeyFieldsMixin: require('./KeyFieldsMixin'),
  Subrequests:    require('./Subrequests')
});