// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/Pipeline/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pipeline',
  class Pipeline extends Neptune.PackageNamespace {}
);
