# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Core/Pipeline/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pipeline', class Pipeline extends Neptune.PackageNamespace)
