# generated by Neptune Namespaces v0.3.0
# file: tests/art/ery/index.coffee

(module.exports = require './namespace')
.addModules
  Filters:                require './filters'
  PipelineClient:         require './pipeline_client'
  PipelineCustomRequests: require './pipeline_custom_requests'
  Request:                require './request'
  Response:               require './response'
  SimplePipeline:         require './simple_pipeline'