# generated by Neptune Namespaces v0.3.0
# file: tests/art/ery/index.coffee

(module.exports = require './namespace')
.addModules
  ArteryClientBasics: require './artery_client_basics'
  ArteryFilters:      require './artery_filters'
  Request:            require './request'
  Response:           require './response'
  SimpleArtery:       require './simple_artery'
require './filters'