# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/namespace.coffee

Art = require '../namespace'
module.exports = Art.Ery ||
Art.addNamespace 'Ery', class Ery extends Neptune.Base
  ;
require './Both/namespace';
require './ClientServer/namespace';
require './Core/namespace'