# generated by Neptune Namespaces v3.x.x
# file: Art.Ery/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Ery', class Ery extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Filters/namespace'