// generated by Neptune Namespaces v4.x.x
// file: Art.Ery/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Ery',
  (class Ery extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Filters/namespace');