# generated by Neptune Namespaces v0.4.1
# file: art/ery/filters/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Filters ||
Ery.addNamespace 'Filters', class Filters extends Neptune.Base
  ;