# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Pipeline/index.coffee

module.exports = require './namespace'
.addModules
  CustomRequests: require './CustomRequests'
  Handlers:       require './Handlers'      