# generated by Neptune Namespaces v0.5
# file: tests/art/ery/Pipeline/index.coffee

module.exports = require './namespace'
.addModules
  Client:         require './Client'        
  CustomRequests: require './CustomRequests'