# generated by Neptune Namespaces v0.5
# file: tests/art/ery/Pipeline/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Pipeline ||
Ery.addNamespace 'Pipeline', class Pipeline extends Neptune.Base
  ;