# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Pipeline/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Pipeline ||
Ery.addNamespace 'Pipeline', class Pipeline extends Neptune.Base
  ;