# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/ClientServer/index.coffee

module.exports = require './namespace'
.addModules
  AuthRequests:           require './AuthRequests'          
  ClientFailures:         require './ClientFailures'        
  CompoundKeys:           require './CompoundKeys'          
  DataUpdatesFilter:      require './DataUpdatesFilter'     
  FilterLocationRequests: require './FilterLocationRequests'
  MyRemoteRequests:       require './MyRemoteRequests'      
  Sessions:               require './Sessions'              
  StaticAssets:           require './StaticAssets'          
require './Pipelines'