# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/ClientServer/index.coffee

module.exports = require './namespace'
.addModules
  AuthRequests:           require './AuthRequests'          
  FilterLocationRequests: require './FilterLocationRequests'
  RemoteRequests:         require './RemoteRequests'        
require './Pipelines'