# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/ClientServer/index.coffee

module.exports = require './namespace'
.addModules
  AuthRequests:           require './AuthRequests'          
  FilterLocationRequests: require './FilterLocationRequests'
  MyRemoteRequests:       require './MyRemoteRequests'      
  StaticAssets:           require './StaticAssets'          
require './Pipelines'