# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/ClientServer/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.ClientServer ||
Ery.addNamespace 'ClientServer', class ClientServer extends Neptune.Base
  ;
require './Pipelines/namespace'