// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/index.js

(module.exports = require('./namespace'))

.addModules({
  MemStorePipeline: require('./MemStorePipeline')
});
require('./Both');
require('./ClientServer');
require('./Core');