# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  MemStorePipeline: require './MemStorePipeline'
require './Both'
require './ClientServer'
require './Core'