// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Ery',
  (class Ery extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Both/namespace');
require('./ClientServer/namespace');
require('./Core/namespace');