# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/namespace.coffee

module.exports = (require '../namespace').addNamespace('Art.Ery', class Ery extends Neptune.PackageNamespace)
require './Both/namespace';
require './ClientServer/namespace';
require './Core/namespace'