// generated by Neptune Namespaces v4.x.x
// file: Art.Ery/.Server/namespace.js

module.exports = require('../namespace').addNamespace(
  'Server',
  class Server extends Neptune.PackageNamespace {}
);
