# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Both/Filters/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AfterEventsFilter:       require './AfterEventsFilter'      
  CreateDatabaseFilters:   require './CreateDatabaseFilters'  
  LinkFieldsFilter:        require './LinkFieldsFilter'       
  LinkFieldsFilter2:       require './LinkFieldsFilter2'      
  LinkFieldsFilterInclude: require './LinkFieldsFilterInclude'
  TimestampFilter:         require './TimestampFilter'        
  UniqueIdFilter:          require './UniqueIdFilter'         
  UserOwnedFilter:         require './UserOwnedFilter'        
  UuidFilter:              require './UuidFilter'             
  ValidationFilter:        require './ValidationFilter'       