// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/Filters/index.js

(module.exports = require('./namespace'))

.addModules({
  AfterEventsFilter:       require('./AfterEventsFilter'),
  CreateDatabaseFilters:   require('./CreateDatabaseFilters'),
  LinkFieldsFilter:        require('./LinkFieldsFilter'),
  LinkFieldsFilter2:       require('./LinkFieldsFilter2'),
  LinkFieldsFilterInclude: require('./LinkFieldsFilterInclude'),
  TimestampFilter:         require('./TimestampFilter'),
  UniqueIdFilter:          require('./UniqueIdFilter'),
  UserOwnedFilter:         require('./UserOwnedFilter'),
  UuidFilter:              require('./UuidFilter'),
  ValidationFilter:        require('./ValidationFilter')
});