// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/Filters/namespace.js

module.exports = require('../namespace').addNamespace(
  'Filters',
  class Filters extends Neptune.PackageNamespace {}
);
