# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Both/Filters/namespace.coffee

module.exports = (require '../namespace').addNamespace('Filters', class Filters extends Neptune.PackageNamespace)
