# generated by Neptune Namespaces v1.x.x
# file: Art/Ery/.Flux/index.coffee

module.exports = require './namespace'
.addModules
  ArtEryFluxModel:      require './ArtEryFluxModel'     
  ArtEryQueryFluxModel: require './ArtEryQueryFluxModel'