# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/.Flux/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Flux ||
Ery.addNamespace 'Flux', class Flux extends Neptune.Base
  ;
