# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/Both/Filters/index.coffee

module.exports = require './namespace'
.addModules
  AfterEventsFilter: require './AfterEventsFilter'
  LinkFieldsFilter:  require './LinkFieldsFilter' 
  TimestampFilter:   require './TimestampFilter'  
  Tools:             require './Tools'            
  UniqueIdFilter:    require './UniqueIdFilter'   
  UserOwnedFilter:   require './UserOwnedFilter'  
  UuidFilter:        require './UuidFilter'       
  ValidationFilter:  require './ValidationFilter' 