# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Both/Filters/namespace.coffee

Both = require '../namespace'
module.exports = Both.Filters ||
Both.addNamespace 'Filters', class Filters extends Neptune.Base
  ;