// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  Filters:             require('./Filters'),
  PrefetchedRecords:   require('./PrefetchedRecords'),
  Request:             require('./Request'),
  RequestResponseBase: require('./RequestResponseBase'),
  Response:            require('./Response'),
  Session:             require('./Session')
});
require('./Pipeline');