# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Core/namespace.coffee

module.exports = (require '../namespace').addNamespace('Core', class Core extends Neptune.PackageNamespace)
require './Pipeline/namespace'