// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/namespace.js

module.exports = require('../namespace').addNamespace(
  'Core',
  class Core extends Neptune.PackageNamespace {}
);
require('./Pipeline/namespace');