# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Both/Flux/index.coffee

module.exports = require './namespace'
.addModules
  ArtEryFluxModel:      require './ArtEryFluxModel'     
  ArtEryQueryFluxModel: require './ArtEryQueryFluxModel'