# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/Both/Flux/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArtEryFluxModel:      require './ArtEryFluxModel'     
  ArtEryQueryFluxModel: require './ArtEryQueryFluxModel'