# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/Both/Flux/namespace.coffee

Both = require '../namespace'
module.exports = Both.Flux ||
Both.addNamespace 'Flux', class Flux extends Neptune.Base
  ;