# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/Both/index.coffee

module.exports = require './namespace'
.addModules
  AuthPipeline:   require './AuthPipeline'  
  Config:         require './Config'        
  FilterBase:     require './FilterBase'    
  SimplePipeline: require './SimplePipeline'
require './Filters'
require './Flux'