# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/Both/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Both ||
Ery.addNamespace 'Both', class Both extends Neptune.Base
  ;
require './Filters/namespace';
require './Flux/namespace'