# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Both/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Both ||
Ery.addNamespace 'Both', class Both extends Neptune.Base
  ;