# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/ClientServer/Pipelines/index.coffee

module.exports = require './namespace'
.addModules
  Auth:                      require './Auth'                     
  ClientFailures:            require './ClientFailures'           
  DataUpdatesFilterPipeline: require './DataUpdatesFilterPipeline'
  FilterLocation:            require './FilterLocation'           
  MyRemote:                  require './MyRemote'                 