# generated by Neptune Namespaces v2.x.x
# file: tests/art/ery/ClientServer/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Auth:                      require './Auth'                     
  ClientFailures:            require './ClientFailures'           
  CompoundKeys:              require './CompoundKeys'             
  DataUpdatesFilterPipeline: require './DataUpdatesFilterPipeline'
  FilterLocation:            require './FilterLocation'           
  MyRemote:                  require './MyRemote'                 
  SimpleStore:               require './SimpleStore'              