# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/ClientServer/Pipelines/namespace.coffee

ClientServer = require '../namespace'
module.exports = ClientServer.Pipelines ||
ClientServer.addNamespace 'Pipelines', class Pipelines extends Neptune.Base
  ;