# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Filters/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Filters ||
Ery.addNamespace 'Filters', class Filters extends Neptune.Base
  ;
