# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/ClientServer/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Auth:                      require './Auth'                     
  ClientFailures:            require './ClientFailures'           
  CompoundKeys:              require './CompoundKeys'             
  DataUpdatesFilterPipeline: require './DataUpdatesFilterPipeline'
  FilterLocation:            require './FilterLocation'           
  MessageRemote:             require './MessageRemote'            
  MyRemote:                  require './MyRemote'                 
  SimpleStore:               require './SimpleStore'              
  UserRemote:                require './UserRemote'               
require './Transition'