# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Both/Pipeline/namespace.coffee

Both = require '../namespace'
module.exports = Both.Pipeline ||
Both.addNamespace 'Pipeline', class Pipeline extends Neptune.Base
  ;