# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery/Both/Flux/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArtEryFluxModel:      require './ArtEryFluxModel'     
  ArtEryQueryFluxModel: require './ArtEryQueryFluxModel'