// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/Flux/index.js

(module.exports = require('./namespace'))

.addModules({
  ArtEryFluxModel:      require('./ArtEryFluxModel'),
  ArtEryQueryFluxModel: require('./ArtEryQueryFluxModel')
});