// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/Flux/namespace.js

module.exports = require('../namespace').addNamespace(
  'Flux',
  class Flux extends Neptune.PackageNamespace {}
);
