# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/Core/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Core ||
Ery.addNamespace 'Core', class Core extends Neptune.Base
  ;